In [4]:
l = []
for a in range(0,101,2):
    print(a, end= ' ')

0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 

In [5]:
n = [x for x in range(1,101,3)]
print(n)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100]


In [6]:
s = [x*x for x in range(1,11)]
print(s)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [7]:
v = [2**x for x in range(1,6)]
print(v)

[2, 4, 8, 16, 32]


In [8]:
wo = ['name','same','fame']
l = [w[0] for w in wo]
print(l)

['n', 's', 'f']


In [15]:
#Common elements present in the list
l1 = [1,2,3,5,6,8,]
l2 =[1,2,3,4,5,7]
l = [i for i in l1 if i not in l2]
print(l)

[6, 8]


In [2]:
n = 0

while n < 3:
    print('No')
    n = n+1

No
No
No


In [5]:
x = ['list',101,10.1,True]

for i in x:
    print(i)

list
101
10.1
True


In [6]:
for i in [2,3,45,675]:
    print(i)

2
3
45
675


In [8]:
n = 1 

while n < 5:
    print('Hello')
    n = n+1
    if n == 4:
        break

Hello
Hello
Hello


In [9]:
n = 1

while n < 5:
    if n == 2:
        n = n+1
        continue
    print("jelllo")
    n = n+1

jelllo
jelllo
jelllo


In [2]:
l = [1,2,3,4,5]
l1 = [c**2 for c in l]
print(l1)

[1, 4, 9, 16, 25]


In [5]:
s = ['a','bvvv','Hive','twelve','cc','asd']

[x.upper() for x in s if len(x) >3]


['BVVV', 'HIVE', 'TWELVE']

In [11]:
re = [1,3,4,5,6]
for x in re:
    if x>3:
        print(x)

4
5
6


In [16]:
[x.upper() for x in ['a',['Tag','Some','Wordsdsf'],'bvvv','Hive','twelve','cc','asd'] if len(x) >4]

['TWELVE']

In [19]:
d = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

r = [n for ns in d for n in ns if n.count('e') >=2]
r

['Steven']

In [22]:
t = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

f = [x for tu in t for x in tu]
f
print(type(x))
print(type(t))

<class 'int'>
<class 'list'>


In [24]:
def fun():
    a = []
    for i in range(5):
        a.append(i)
    

In [25]:
import numpy as np


In [28]:
arr = np.arange(100)
arr
type(arr)

numpy.ndarray

In [37]:
d = np.random.randn(2,4)
d*10
d +d

array([[-1.59886617,  5.76147576, -0.59057045,  0.13454691],
       [-0.27242808, -1.13709985, -2.80605695, -0.66104659]])

In [39]:
d.shape

(2, 4)

In [40]:
d.dtype

dtype('float64')

In [43]:
#Creating one dimensional array:

d1 = [6,3,5,6,7,8,9,2,4,5,67,2,1]
print(type(d1))
arr = np.array(d1)
arr

<class 'list'>


array([ 6,  3,  5,  6,  7,  8,  9,  2,  4,  5, 67,  2,  1])

In [52]:
#Creating multi-dimensional array:

d = [[1,2,3],[4,5,6]]
arr = np.array(d)
arr.dtype
arr.ndim
arr.shape


(2, 3)

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [74]:
np.zeros((3,3,3),dtype = np.bool)

C:\Users\opandey2\AppData\Local\Temp\ipykernel_25556\1963536838.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3,3,3),dtype = np.bool)


array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [65]:
a = np.array([1,2,3], dtype = np.float64)
a.dtype

dtype('float64')

In [73]:
a = np.array([1,2,3], dtype = np.int64)
a

array([1, 2, 3], dtype=int64)

In [82]:
#Converting float to integer

a = np.array([1,2,3,4,5])
a.dtype
f = a.astype(np.float64)
f
f.dtype

dtype('float64')

In [90]:
#Indexing and sorting

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a[5::-1]

array([5, 4, 3, 2, 1, 0])

In [136]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [137]:
d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
old = d[0].copy()


In [139]:
d[0] = 42
d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [141]:
d[0] = old
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [156]:
#Transporting data:

a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [157]:
#T is a in-built python keyword for transportation of array:

a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [158]:
import pandas as pd

In [162]:
df = pd.read_csv(r"C:\Users\opandey2\Desktop\Netflix subscription fee Dec-2021.csv")
df

Country_code         Country  Total Library Size  No. of TV Shows  \
0            ar       Argentina                4760             3154   
1            au       Australia                6114             4050   
2            at         Austria                5640             3779   
3            be         Belgium                4990             3374   
4            bo         Bolivia                4991             3155   
..          ...             ...                 ...              ...   
60           ua         Ukraine                5336             3261   
61           gb  United Kingdom                6643             4551   
62           us   United States                5818             3826   
63           uy         Uruguay                4989             3154   
64           ve       Venezuela                4797             3154   

    No. of Movies  Cost Per Month - Basic ($)  Cost Per Month - Standard ($)  \
0            1606                        3.74                           6.30   
1            2064                        7.84                          12.12   
2            1861                        9.03                          14.67   
3            1616                       10.16                          15.24   
4            1836                        7.99                          10.99   
..            ...                         ...                            ...   
60           2075                        5.64                           8.46   
61           2092                        7.91                          13.20   
62           1992                        8.99                          13.99   
63           1835                        8.99                          12.99   
64           1643                        7.99                          10.99   

    Cost Per Month - Premium ($)  
0                           9.26  
1                          16.39  
2                          20.32  
3                          20.32  
4                          13.99  
..                           ...  
60                         11.29  
61                         18.48  
62                         17.99  
63                         15.99  
64                         13.99  

[65 rows x 8 columns]

In [163]:
df.shape

(65, 8)

In [166]:
df.isnull().sum()

Country_code                     0
Country                          0
Total Library Size               0
No. of TV Shows                  0
No. of Movies                    0
Cost Per Month - Basic ($)       0
Cost Per Month - Standard ($)    0
Cost Per Month - Premium ($)     0
dtype: int64

In [167]:
df.mean()

C:\Users\opandey2\AppData\Local\Temp\ipykernel_25556\3698961737.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()


Total Library Size               5314.415385
No. of TV Shows                  3518.953846
No. of Movies                    1795.461538
Cost Per Month - Basic ($)          8.368462
Cost Per Month - Standard ($)      11.990000
Cost Per Month - Premium ($)       15.612923
dtype: float64

In [169]:
np.sum(df)

Country_code                     arauatbebobrbgcaclcocrhrczdkeceefifrdegigrgthn...
Country                          ArgentinaAustraliaAustriaBelgiumBoliviaBrazilB...
Total Library Size                                                          345437
No. of TV Shows                                                             228732
No. of Movies                                                               116705
Cost Per Month - Basic ($)                                                  543.95
Cost Per Month - Standard ($)                                               779.35
Cost Per Month - Premium ($)                                               1014.84
dtype: object

In [171]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
f = pd.DataFrame(data)
f

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [173]:
f.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [176]:
pd.DataFrame(data, columns = ['state','pop'])#To select only specific columns

state  pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  3.6
3  Nevada  2.4
4  Nevada  2.9
5  Nevada  3.2

In [184]:
f['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [185]:
f.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [188]:
f['dept'] = 13
f

state  year  pop  dept
0    Ohio  2000  1.5    13
1    Ohio  2001  1.7    13
2    Ohio  2002  3.6    13
3  Nevada  2001  2.4    13
4  Nevada  2002  2.9    13
5  Nevada  2003  3.2    13