In [2]:
import numpy as np
import pandas as pd


In [3]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/opandey2/AppData/Local/anaconda3\\Library\\lib

In [7]:
z = np.ones(10, dtype = 'int')
y = np.zeros(10)
print(z)
print(y)

[1 1 1 1 1 1 1 1 1 1]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
z = np.arange(30)
z[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [18]:
#Creating a reshape(3,3) 3x3 matrix by using arange function 

z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

In [25]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
z = np.random.random((3,3,3))
z

array([[[0.82408082, 0.84999006, 0.95183624],
        [0.92813067, 0.67634157, 0.79342776],
        [0.7981167 , 0.06162148, 0.62477754]],

       [[0.09435583, 0.19339312, 0.39318971],
        [0.48295783, 0.97949378, 0.29618253],
        [0.3459734 , 0.39234643, 0.3332681 ]],

       [[0.58746019, 0.22062697, 0.50315607],
        [0.12552996, 0.23683405, 0.31680916],
        [0.35090773, 0.06874674, 0.06427202]]])

In [30]:
z =np.random.random((10,10))
zm, zx = z.min(),z.max()
print(zm,zx)

0.0036753513484040212 0.9966122180677506


In [31]:
z = np.random.random(30)
m = z.mean()
m

0.4699284111301312

In [46]:
z = np.random.random((2,2))
z.max()

0.7514394317593335

In [48]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
print(sum(range(5),-1))

9


In [70]:
z = np.random.random(10)
#z**z
#2 << z >> 2
#1j*z
#z/1/1
#z<z>z
z <-z

array([False, False, False, False, False, False, False, False, False,
       False])