In [140]:
#Import the numpy package under the name np


import numpy as np

In [142]:
# Print the numpy version

np.__version__

'1.24.3'

In [15]:
np.size(n)

6

In [17]:
np.array({1,2,4,4,5,5}).shape

()

In [21]:
arr = np.array([[1,1,1,1,1],[2,3,5,6,6]])
arr.shape

(2, 5)

In [25]:
##Indexing and slicing 

arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [27]:
arr1[arr1>5]


array([6, 7, 8, 9])

In [32]:
arr1[arr1==4]

array([4])

In [35]:
arr1[arr1>8].shape

(1,)

In [36]:
a = np.array([1,2,3,4,5])

In [39]:
li = [1,1,1,1,1,2]

In [43]:
li[0]=10
li

[10, 1, 1, 1, 1, 2]

In [47]:
#Array Manipulation

In [62]:
ar2 = np.array([[12,3,4],[1,2,3,],[1,2,3]])

In [63]:
ar2.shape

(3, 3)

In [73]:
import numpy as np

In [74]:
np.__version__

'1.24.3'

In [79]:
##3. Create a null vector of size 10

np.zeros(10).size

10

In [144]:
#4. How to find the memory size of any array

z = np.zeros((10,10))
z.size

100

In [143]:
# How to get the documentation of the numpy add function from the command line?

np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

In [86]:
#6. Create a null vector of size 10 but the fifth value which is 1

n = np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [145]:
#7. Create a vector with values ranging from 10 to 49

np.arange(10,50)
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [146]:
##8. Reverse a vector (first element becomes last) 

z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [147]:
##8. Reverse a vector (first element becomes last) 

a = np.arange(50)
a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [150]:
##9. Create a 3x3 matrix with values ranging from 0 to 8

z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [157]:
##Reshape continue

z = np.arange(10).reshape(2,5)
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [156]:
##10. Find indices of non-zero elements from [1,2,0,0,4,0]

nz = np.nonzero([1,2,0,0,0,4,0])
nz

(array([0, 1, 5], dtype=int64),)

In [159]:
##11. Create a 3x3 identity matrix 

z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [160]:
##12. Create a 3x3x3 array with random values 

np.random.random((3,3,3))

array([[[0.82719637, 0.54081454, 0.45695419],
        [0.69729508, 0.26463856, 0.58598448],
        [0.01463173, 0.01289286, 0.38320057]],

       [[0.1124016 , 0.83230182, 0.36731565],
        [0.47180848, 0.40417986, 0.84367126],
        [0.13581763, 0.67370834, 0.56611231]],

       [[0.27634781, 0.06037614, 0.87791598],
        [0.95669058, 0.36745322, 0.76931926],
        [0.49906363, 0.62159533, 0.04243625]]])

In [162]:
##13. Create a 10x10 array with random values and find
#the minimum and maximum values

z = np.random.random((10,10))
zm, zx = z.min(),z.max()
print(zm,zx)

0.005773124406387331 0.9897981183389675


In [163]:
##14. Create a random vector of size 30 and find the mean value

z = np.random.random(30)
me = z.mean()
me

0.5135217650904824

In [133]:
##Create 2d array with 1 on the border and 0 inside.

z = np.ones((10,10))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [165]:
##2D array with 0 inside and 1 on the border.
z = np.ones((5,5))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])